# Generated by Django 2.1.7 on 2019-03-12 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelfapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-date_added']},
        ),
    ]
